apiVersion: ec2.aws.crossplane.io/v1beta1
kind: NATGateway
metadata:
  name: nat-gateway
spec:
  forProvider:
    region: eu-central-1
    allocationIdRef:
      name: natgateway-eip
    subnetIdRef:
      name: public-subnet-az1
    tags:
      - key: Name
        value: nat-gateway
  providerConfigRef:
    name: aws-provider-config
