apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: private-subnet-az1
  labels:
    name: private-subnet-az1
spec:
  forProvider:
    region: eu-central-1
    availabilityZone: eu-central-1a
    vpcIdSelector:
      matchLabels:
        name: vpc
    cidrBlock: 10.200.0.0/18
    tags:
      - key: Name
        value: private-subnet-az1
  providerConfigRef:
    name: aws-provider-config
