apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: vpc
  labels:
    name: vpc
spec:
  forProvider:
    region: eu-central-1
    cidrBlock: 10.200.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
      - key: Name
        value: vpc
  providerConfigRef:
    name: aws-provider-config
